### ISSUE TITLE
is this buildable?

### ISSUE THREAD

**Issue by WH0LEWHALE** [BigMark824/fixed-sixteensrc#1]

**Comment by BigMark824** [comment]
This isn't an issue, but yes it is entirely buildable.

**Comment by WH0LEWHALE** [comment]
what depends do i need? thanks for the frickin fast answer.

**Comment by BigMark824** [comment]
All g bro, you need your own contrib. I'll get sued if I provide that stuff :sob:

**Comment by WH0LEWHALE** [comment]
okay, i will use what yakov's(original unmodified source) dependencies list then.

**Comment by WH0LEWHALE** [comment]
'then': is not a member of 'boost::shared_future<std::string>' what am i doing wrong?

**Comment by WH0LEWHALE** [comment]
can you atleast say the contrib folder names and version?
